### ISSUE TITLE
How to enable a normal eraser?

### ISSUE THREAD

**Issue by bapillai** [dilidili/react-drawing-board#1]
I want to be able to erase just a small section of my drawing or entry.How do i enable the same?

**Comment by dilidili** [comment]
@bapillai it does not support now, but i can add it lately.

**Comment by bapillai** [comment]
@dilidili that would be really helpful.Another question i had was,is there any way to collapse the toolbar or have it vertically aligned on left or right, rather than on the top

**Comment by bapillai** [comment]
@dilidili is there an ETA on when i can expect the eraser component enabled and checked in?

**Comment by dilidili** [comment]
> p



> @dilidili that would be really helpful.Another question i had was,is there any way to collapse the toolbar or have it vertically aligned on left or right, rather than on the top

i would export some props to control the style of drawing board, maybe on today or tomorrow.

**Comment by dilidili** [comment]
@bapillai version 0.2.0 add Eraser Tool and support className and toolbarPlacement.
Check the demo https://react-drawing-board-demo.now.sh/.

**Comment by bapillai** [comment]
This works! Thanks a lot for the quick response
