### ISSUE TITLE
onSave image size

### ISSUE THREAD

**Issue by ahmetozalp** [dilidili/react-drawing-board#10]
Hello,

I have a question I want to ask thank you for the project.
Every time I press the save button, the size of the picture changes and it grows many times.

2550x1920 3th save
![0_SW_DOKUNMA_26 11 2020 14:26:37 3](https://user-images.githubusercontent.com/7665820/100346104-5e90b680-2ff4-11eb-8109-4e8a457f3608.jpg)

1280x960 2th save
![0_SW_DOKUNMA_26 11 2020 14:26:37 2](https://user-images.githubusercontent.com/7665820/100346113-60f31080-2ff4-11eb-8364-3523ec79de3b.jpg)

640x480 Pure size
![0_SW_DOKUNMA_26 11 2020 14:26:37](https://user-images.githubusercontent.com/7665820/100346120-62bcd400-2ff4-11eb-9f38-b8e006e3068f.jpg)

**Comment by ahmetozalp** [comment]
window.devicePixelRatio to 1 and fixed

**Comment by dilidili** [comment]
could you provide an online demo so that i can debug on it.

**Comment by ahmetozalp** [comment]
Since it is a company project, the demo may be a problem.
