### ISSUE TITLE
Not working for mobile users

### ISSUE THREAD

**Issue by karthikwebdev** [dilidili/react-drawing-board#2]
this package is really awesome in case of desktop users,but not working for mobile users. how can i fix that?

**Comment by dilidili** [comment]
@karthikwebdev  Thank you for your compliment. I'll take your advice into account with next release, maybe on 26th this week.

**Comment by Vijay-mRoads** [comment]
@dilidili Great library. Do you have an update on this issue?

**Comment by dilidili** [comment]
@karthikwebdev @Vijay-mRoads  version 0.3.0 supports mobile devices now! can try it on [https://react-drawing-board-demo.dilidili.now.sh/](https://react-drawing-board-demo.dilidili.now.sh/) from mobile user agent.

**Comment by vjkrishna21** [comment]
Thanks, @dilidili. It's working for me. Can you please add the documentation on how to build it? I am getting compilation errors when I try to build it for development purposes. Do you want me to open a different issue for this?

**Comment by dilidili** [comment]
> Thanks, @dilidili. It's working for me. Can you please add the documentation on how to build it? I am getting compilation errors when I try to build it for development purposes. Do you want me to open a different issue for this?

```npm install && npm run dev``` should work. If not, please open another issue and post an error log.
