### ISSUE TITLE
Repository fork can't be used as a dependency

### ISSUE THREAD

**Issue by gabrielguilhoto** [dilidili/react-drawing-board#21]
I forked the repository and added it as a dependency of another project, but I would get the following error message: `Module not found: Error: Can't resolve 'react-drawing-board'`. I found that was happening because the "compiled" files on the lib directory, such as plain JS and CSS files, were absent. Only the src directory, which had TypeScript and Less files, was present.

I found out that the problem could be solved if the library defined a `prepare` script on `package.json` (see https://stackoverflow.com/a/57829251/12440938). I'll open a PR with that change.

**Comment by dilidili** [comment]
Hi @gabrielguilhoto, thanks for PR and I update the package with version ```0.4.6```.
