### ISSUE TITLE
Notify when zoom changes, Feature Request

### ISSUE THREAD

**Issue by vjkrishna21** [dilidili/react-drawing-board#5]
Hey,

I am trying to build a shared drawing board. Currently, I am facing an issue with shared zoom because no event is fired when zoom is changed. Is it possible to trigger an event when zoom is changed?

Thank you!

**Comment by dilidili** [comment]
@vjkrishna21 i counld provide controlled viewMatrix related props. It contains translate and scale actions, is it enough?

**Comment by vjkrishna21** [comment]
Actually, when I get the zoom change event, it is broadcasted to other participants viewing the drawing board. Whatever value that you'll be providing, will be fed to the component again to change the zoom. 

Example:

If you return the **zoom%** when the zoom changes, it will be broadcasted to other users. So, the component should accept a prop for **zoom%**.

**Comment by dilidili** [comment]
> Actually, when I get the zoom change event, it is broadcasted to other participants viewing the drawing board. Whatever value that you'll be providing, will be fed to the component again to change the zoom.
> 
> Example:
> 
> If you return the **zoom%** when the zoom changes, it will be broadcasted to other users. So, the component should accept a prop for **zoom%**.

OK, got it. I'll add it soon later.

**Comment by dilidili** [comment]
@vjkrishna21 I've expose ```viewMatrix``` and ```onViewMatrixChange``` props, you can use them to control the perspective on version 0.3.4.
